esphome:
  name: esp-test
  friendly_name: esp_test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    static_ip: 
    gateway: 
    subnet: 
  use_address: 


captive_portal:

mdns:
  disabled: true
    

output:
  - platform: gpio
    id: "lil_led"
    pin: 13

light:
  - platform: binary
    output: "lil_led"
    name: "little_led"
